name: Mypy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        pip install mypy types-requests
    - name: mypy
      run: |
        mypy --ignore-missing-imports ./src
